name: Build Nuxeo Statistic Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        server-id: maven-internal
        server-username: MAVEN_USERNAME
        server-password: MAVEN_TOKEN # env variable for token  
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven (build/tests/package)
      run: mvn clean install
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
    - name: Upload MP package
      uses: wei/curl@v1
      with:
        args: -i -u ${{ secrets.CONNECT_LOGIN }}:${{ secrets.CONNECT_TOKEN }} -F package=@package/target/nuxeo-statistics-package-1.0-SNAPSHOT.zip "https://connect.nuxeo.com/nuxeo/site/marketplace/upload?batch=true&orgId=nuxeo"
